apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.32
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: capstone-mysql-pvc
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: password
        - name: MYSQL_DATABASE
          value: "test_DB"
      volumes:
        - name: capstone-mysql-pvc
          persistentVolumeClaim:
            claimName: capstone-mysql-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: hyunjun1325/node:0.11
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: mysql-service.default.cluster.local
        command: ["/bin/bash","-ec", "while :; do sleep 5; done"]
