apiVersion: v1
kind: PersistentVolume
metadata:
  name: capstone-mysql-pv
  # namespace: capstone
  namespace: default
spec:
  storageClassName: capstone-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/capstone_mysql"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: capstone-web-test-pv
  # namespace: capstone
  namespace: default
spec:
  storageClassName: capstone-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/capstone_web_test"
  persistentVolumeReclaimPolicy: Retain
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: capstone-web-test-pv-2
  # namespace: capstone
  namespace: default
spec:
  storageClassName: capstone-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/capstone_web_test_2"
  persistentVolumeReclaimPolicy: Retain


