apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capstone-mysql-pvc
  namespace: capstone
spec:
  storageClassName: capstone-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
