apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capstone-mysql-pvc
  # namespace: capstone
  namespace: default
spec:
  storageClassName: capstone-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capstone-web-test-pvc
  # namespace: capstone
  namespace: default
spec:
  storageClassName: capstone-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
